// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import sqlx "github.com/jmoiron/sqlx"

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

// Connection provides a mock function with given fields:
func (_m *DB) Connection() *sqlx.DB {
	ret := _m.Called()

	var r0 *sqlx.DB
	if rf, ok := ret.Get(0).(func() *sqlx.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.DB)
		}
	}

	return r0
}
